In [1]:
# Load in Packages
import pandas as pd
from google.colab import files

In [5]:
import pandas as pd

# Load in the data
inpatient_data = pd.read_csv("/Cleaned_InpatientLog.csv")
outpatient_data = pd.read_csv("/Cleaned_OutPatientLog.csv")

In [7]:
inpatient_data.head()

,Provider Name,Admit Date,Discharge Date,Mo/Yr,Acct. Number,DRG Code,Specialty,Payor Group,Net Payments,Expected Payments,Pharmacy Cost,Supply Cost,Actual Implant Cost,Total Supply Costs,Scheduled Procedure,Actual Performed
0,ADAM,1/2/2018,1/3/2018,Jan-18,6478,473,SPINE,BLUE CROSS,29497.500,29497.5,357.072,1092.732,16500.00,17949.804,ACDF,ANTERIOR CERVICAL DISCECTOMY AND FUSION C4-6 W...
1,ADAM,1/2/2018,1/3/2018,Jan-18,6572,473,SPINE,LEGAL/OTHER,133844.250,82371.0,281.196,880.080,36480.00,37641.276,ACDF,ANTERIOR CERVICAL DISCECTOMY AND FUSION C5-6 W...
2,JOEL,1/3/2018,1/6/2018,Jan-18,5856,460,SPINE,MEDICARE,31697.955,31380.0,630.240,601.584,13366.80,14598.624,PLF,"HWR XIA III, L4-5, L2-S1 DECOMP. PLF L2-S1 & L..."
3,JAMES,1/5/2018,1/8/2018,Jan-18,6188,460,SPINE,MEDICARE,31697.955,31380.0,523.284,775.848,18451.92,19751.052,PLF,"HW REVISION, DECOMPRESSION T12-L1, EXTENSION O..."
4,CHARLES,1/7/2018,1/9/2018,Jan-18,6942,486,ORTHO,BLUE CROSS,17933.850,17706.0,422.808,1781.052,2133.00,4336.860,I&DKNEE,LEFT KNEE WASHOUT AND LINER EXCHANGE

In [8]:
outpatient_data.head()

,Provider Name,Admit Date,Discharge Date,Mo/Yr,Acct. Number,Account Type,Specialty,Payor Group,Adjusted Net Payments,Pharmacy Cost,Supply Cost,Actual Implant Cost per Log,Total Supply Costs,Scheduled Procedure,Actual Performed
0,ADAM,1/2/2018,1/3/2018,Jan-18,6596,O OBS,PAIN SURG,OTHER GOVERNMENT,34423.200,145.176,1680.792,30360.0,32185.968,LUMLAMWSCS,SCS LAMI PLACEMENT-BOSTON
1,ADAM,1/2/2018,1/2/2018,Jan-18,6287,O PMVSTM,PAIN SURG,WORK COMP,80082.405,117.420,1402.128,23040.0,24559.548,REVSCS,"SCS BATTERY EXCHANGE, POCKET CHANGE"
2,TIMOTHY,1/2/2018,1/2/2018,Jan-18,6802,O PMVINJ,PAIN INJ,MEDICARE,907.650,0.000,19.092,0.0,19.092,LESI,LUMBAR EPIDURAL STERIOD INJECTION
3,TIMOTHY,1/2/2018,1/2/2018,Jan-18,6804,O PMVINJ,PAIN INJ,BLUE CROSS,1350.960,1.824,70.908,0.0,72.732,NRB,RIGHT L5 NERVE ROOT BLOCK
4,JOHN,1/3/2018,1/3/2018,Jan-18,6865,O PMVINJ,PAIN INJ,MEDICARE,2137.515,0.000,53.016,0.0,53.016,CESI,"CERVICAL EPIDURAL STEROID INJECTION, trigger p..."

In [9]:
inpatient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7435 entries, 0 to 7434
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Provider Name        7435 non-null   object
 1   Admit Date           7435 non-null   object
 2   Discharge Date       7435 non-null   object
 3   Mo/Yr                7435 non-null   object
 4   Acct. Number         7435 non-null   int64
 5   DRG Code             7435 non-null   int64
 6   Specialty            7435 non-null   object
 7   Payor Group          7435 non-null   object
 8   Net Payments         7435 non-null   float64
 9   Expected Payments    7435 non-null   float64
 10  Pharmacy Cost        7435 non-null   float64
 11  Supply Cost          7435 non-null   float64
 12  Actual Implant Cost  7435 non-null   float64
 13  Total Supply Costs   7435 non-null   float64
 14  Scheduled Procedure  7435 non-null   object
 15  Actual Performed     7434 non-null   object
dtypes: float64(6), int64(2), object(8)
memory usage: 929.5+ KB

In [10]:
outpatient_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10947 entries, 0 to 10946
Data columns (total 15 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Provider Name                10947 non-null  object
 1   Admit Date                   10947 non-null  object
 2   Discharge Date               10947 non-null  object
 3   Mo/Yr                        10947 non-null  object
 4   Acct. Number                 10947 non-null  int64
 5   Account Type                 10947 non-null  object
 6   Specialty                    10947 non-null  object
 7   Payor Group                  10947 non-null  object
 8   Adjusted Net Payments        10947 non-null  float64
 9   Pharmacy Cost                10947 non-null  float64
 10  Supply Cost                  10947 non-null  float64
 11  Actual Implant Cost per Log  10947 non-null  float64
 12  Total Supply Costs           10947 non-null  float64
 13  Scheduled Procedure          10937 non-null  object
 14  Actual Performed             10937 non-null  object
dtypes: float64(5), int64(1), object(9)
memory usage: 1.3+ MB

In [11]:
outpatient_data.shape

(10947, 15)

In [12]:
inpatient_data.shape

(7435, 16)

In [13]:
print(inpatient_data.isnull().sum())

Provider Name          0
Admit Date             0
Discharge Date         0
Mo/Yr                  0
Acct. Number           0
DRG Code               0
Specialty              0
Payor Group            0
Net Payments           0
Expected Payments      0
Pharmacy Cost          0
Supply Cost            0
Actual Implant Cost    0
Total Supply Costs     0
Scheduled Procedure    0
Actual Performed       1
dtype: int64

In [14]:
print(outpatient_data.isnull().sum())

Provider Name                   0
Admit Date                      0
Discharge Date                  0
Mo/Yr                           0
Acct. Number                    0
Account Type                    0
Specialty                       0
Payor Group                     0
Adjusted Net Payments           0
Pharmacy Cost                   0
Supply Cost                     0
Actual Implant Cost per Log     0
Total Supply Costs              0
Scheduled Procedure            10
Actual Performed               10
dtype: int64

In [15]:
inpatient_data['Acct. Number'].nunique()

5628

In [16]:
outpatient_data['Acct. Number'].nunique()

7254

In [18]:
combined_accounts = pd.concat([inpatient_data['Acct. Number'], outpatient_data['Acct. Number']])
combined_accounts.nunique()

9164

In [21]:
inpatient_data.duplicated().sum()

np.int64(0)

In [20]:
outpatient_data.duplicated().sum()

np.int64(0)

In [22]:
inpatient_data['Admit Date'] = pd.to_datetime(inpatient_data['Admit Date'])
print("Earliest Inpatient Admit:", inpatient_data['Admit Date'].min())
print("Latest Inpatient Admit:", inpatient_data['Admit Date'].max())

Earliest Inpatient Admit: 2018-01-02 00:00:00
Latest Inpatient Admit: 2022-12-30 00:00:00